# Generated by Django 3.1.4 on 2021-03-27 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chatmessage_thread'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterUniqueTogether(
            name='chatmessage',
            unique_together={('thread',)},
        ),
    ]
