# Generated by Django 3.1.4 on 2021-03-27 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210327_1919'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatmessage',
            unique_together={('thread',)},
        ),
    ]
