# Generated by Django 3.1.4 on 2021-03-27 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210327_1921'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatmessage',
            unique_together=set(),
        ),
    ]
